---

name: lint

on: [push, pull_request]

jobs:
  # commitlint:
  #   runs-on: ubuntu-latest
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - uses: wagoid/commitlint-github-action@v4
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: node_modules|.git
          LINTER_RULES_PATH: ./
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_STANDARD: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # lint-others:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Install Node.js, Yarn
  #       run: |
  #         sudo apt-get update \
  #             && sudo apt-get install -y nodejs yarn
  #     - name: Install libsysconfcpus
  #       run: |
  #         if [[ ! -d $HOME/sysconfcpus/bin ]]; then
  #             git clone https://github.com/obmarg/libsysconfcpus.git
  #             pushd libsysconfcpus
  #             ./configure --prefix=$HOME/sysconfcpus
  #             make && make install
  #             popd
  #         fi
  #     - name: Build
  #       run: |
  #         yarn \
  #             && $HOME/sysconfcpus/bin/sysconfcpus --num 2 \
  #                 yarn build:production
  #     - name: Validate HTML
  #       run: yarn html-validate

# ---
# #################################
# #################################
# ## Super Linter GitHub Actions ##
# #################################
# #################################
# name: Lint Code Base

# #############################
# # Start the job on all push #
# #############################
# on:
#   push:
#     branches: [master, main]
#     # Remove the line above to run when pushing to master
#   pull_request:
#     branches: [master, main]

# ###############
# # Set the Job #
# ###############
# jobs:
#   build:
#     # Name the Job
#     name: Lint Code Base
#     # Set the agent to run on
#     runs-on: ubuntu-latest

#     ############################################
#     # Grant status permission for MULTI_STATUS #
#     ############################################
#     permissions:
#       contents: read
#       packages: read
#       statuses: write

#     ##################
#     # Load all steps #
#     ##################
#     steps:
#       ##########################
#       # Checkout the code base #
#       ##########################
#       - name: Checkout Code
#         uses: actions/checkout@v3
#         with:
#           # Full git history is needed to get a proper
#           # list of changed files within `super-linter`
#           fetch-depth: 0

#       ################################
#       # Run Linter against code base #
#       ################################
#       - name: Lint Code Base
#         uses: super-linter/super-linter@v5
#         env:
#           VALIDATE_ALL_CODEBASE: false
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
