name: linter

on: [pull_request]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: node_modules|.git
          LINTER_RULES_PATH: ./
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
